### ISSUE TITLE
🔥Final group capstone: set up your Kanban board [RoR]

### ISSUE THREAD

**Issue by roniy68** [roniy68/capstone-rails#14]
# Highlights 🥇 
<img src="https://media2.giphy.com/media/gEosD4s6fhCUuyfrPC/giphy.gif"/>

## What I have Done
✅ Create an empty repository for your group project.
✅ Setup [GitHub project (Kanban board)](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) in team repo (set up the same columns as in previous group projects).
✅ Create cards based on [the project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md). Each task should be a separate card that:
✅ Each of the team members should assign themselves to the cards (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks).

# Team Members : 
---
## Missed anything?
- [ ] Explained the purpose of this ISSUE.
- [ ] Self reviewed the ISSUE.
- [ ] Added or updated test cases.
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Updated documentation (if applicable).
- [ ] Attached screenshots (if applicable).

## Followed Rules: 
- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
-  Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-  Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

**Comment by Meltrust** [comment]
Hi team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
